# Generated by Django 4.2.6 on 2023-10-15 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artworks',
            fields=[
                ('artwork_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_title', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'yuuzu_artworks',
            },
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('game_id', models.AutoField(primary_key=True, serialize=False)),
                ('game_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'yuuzu_games',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('line_id', models.CharField(max_length=255, unique=True)),
                ('unique_code', models.CharField(max_length=10, null=True, unique=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'yuuzu_users',
            },
        ),
        migrations.CreateModel(
            name='UserGames',
            fields=[
                ('user_game_id', models.AutoField(primary_key=True, serialize=False)),
                ('passed', models.BooleanField(default=False)),
                ('play_date', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ServerCommon.games')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ServerCommon.users')),
            ],
            options={
                'db_table': 'yuuzu_user_games',
            },
        ),
        migrations.CreateModel(
            name='Beacons',
            fields=[
                ('beacon_id', models.AutoField(primary_key=True, serialize=False)),
                ('beacon_uuid', models.CharField(max_length=100)),
                ('artworks', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ServerCommon.artworks')),
            ],
            options={
                'db_table': 'yuuzu_beacons',
            },
        ),
        migrations.CreateModel(
            name='ArtworkItems',
            fields=[
                ('artwork_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('artwork_item_image', models.CharField(max_length=255)),
                ('artwork_item_title', models.CharField(max_length=255)),
                ('artwork_item_description', models.TextField()),
                ('artworks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ServerCommon.artworks')),
            ],
            options={
                'db_table': 'yuuzu_artwork_items',
            },
        ),
    ]
