# Generated by Django 4.2.6 on 2023-10-19 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServerCommon', '0002_beacons_beacon_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beacons',
            name='beacon_uuid',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
