# Generated by Django 4.2.6 on 2023-10-22 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ServerCommon', '0003_alter_beacons_beacon_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beacons',
            name='artworks',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ServerCommon.artworks', unique=True),
        ),
    ]
