# Generated by Django 4.2.6 on 2023-10-25 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ServerCommon', '0004_alter_beacons_artworks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artworkitems',
            name='artworks',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artwork_items', to='ServerCommon.artworks'),
        ),
    ]
