# Generated by Django 4.2.6 on 2023-10-26 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServerCommon', '0005_alter_artworkitems_artworks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artworks',
            name='product_title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
