# Generated by Django 4.2.6 on 2023-10-26 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServerCommon', '0006_alter_artworks_product_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artworkitems',
            name='artwork_item_image',
            field=models.ImageField(upload_to='templates/static/uploads/artworks/'),
        ),
    ]
