# Generated by Django 4.2.6 on 2023-11-17 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ServerCommon', '0009_alter_artworkitems_artwork_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beacons',
            name='artworks',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='ServerCommon.artworks'),
        ),
    ]
