# Generated by Django 4.2.6 on 2024-01-22 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServerCommon', '0012_games_game_diff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='game_diff',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
