# Generated by Django 4.2.6 on 2024-01-28 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServerCommon', '0013_alter_games_game_diff'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='game_diff_select',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
