# Generated by Django 4.2.6 on 2024-01-28 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServerCommon', '0014_games_game_diff_select'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='game_diff_select',
            field=models.IntegerField(null=True),
        ),
    ]
