# Generated by Django 4.2.6 on 2024-01-29 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServerCommon', '0015_alter_games_game_diff_select'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='user_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
