# Generated by Django 4.2.6 on 2024-01-29 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServerCommon', '0016_users_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergames',
            name='play_date',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
