# Generated by Django 4.2.6 on 2024-01-29 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServerCommon', '0017_alter_usergames_play_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergames',
            name='play_date',
            field=models.FloatField(null=True),
        ),
    ]
